### ISSUE TITLE
Search bar in launcher overlays widgets and icons

### ISSUE THREAD

**Issue by aglasgall** [TeamApexQ/apexq#1]
Observed behavior: When I go to place a widget on the top row of any home screen, the Google search bar overlaps it
Expected behavior: The widget should place itself immediately below the search bar (as it did in CM9)

**Comment by aglasgall** [comment]
This also occurs with the bottom row of icons on the home screen and the quick-launch bar.

**Comment by kornyone** [comment]
This should be fixed with https://github.com/TeamApexQ/android_device_samsung_apexq-common/commit/67a783951e6aec5d160e09a6ac8ad8b6c0b9293d

**Comment by aglasgall** [comment]
Confirmed fixed as of this morning; closing
