### ISSUE TITLE
wpa/wpa2 does not work on Wifi Tethering

### ISSUE THREAD

**Issue by kornyone** [TeamApexQ/apexq#14]
Only Open network will successfully tether right now.  We don't have bcmdhd, so the fixes for the D2 do not help us.

**Comment by infernix** [comment]
This has been fixed: https://github.com/TeamApexQ/android_kernel_samsung_apexq/commit/00529bec353dc97de663aa0057faf0d61c3e4c8c and https://github.com/TeamApexQ/android_kernel_samsung_apexq/commit/de5d69fc00f9d614732e803cc47b33b5c09eb93b

**Comment by RenaeMacLeod** [comment]
I cannot get it working with the 2013-10-09 build. It simply says 'Error' in the 'Tethering & portable hotspot' settings page under 'Portable Wi-Fi hotspot'. Open network doesn't work either. Once I try to set it up I can no longer get WiFi working without a reboot.
