### ISSUE TITLE
Driver update for wcnss and prima

### ISSUE THREAD

**Issue by infernix** [TeamApexQ/apexq#16]
(copy pasted from the main wiki page)

Driver update for wcnss and prima. These drivers can be updated by directly pulling in and overwriting the kernel paths drivers/net/wireless/wcnss and drivers/staging/prima from the Nexus 4 LGE Mako kernel on CM: https://github.com/CyanogenMod/lge-kernel-mako.git

In conjunction with the Mako FIRMWARE found here: https://github.com/CyanogenMod/android_device_lge_mako/blob/cm-10.1/WCNSS_qcom_wlan_nv.bin it will load.

Note that this driver appears to OBSOLETE the system/etc/firmware/wcnss.\* files.
It also requires an edit to system/etc/init.qcom.wifi.sh so that it doesn't overwrite the mako firmware and link back to relay firmware.

The driver can be named wlan.sh with an internal name of wlan. I believe that the driver works, it is able to scan perfectly, but does not connect. I suspect different configuration may be required.

I ran out of time, otherwise would have provided these changes via GIT.

**Comment by nardholio** [comment]
Ok this is really weird. The newer prima driver will not load with our current wcnss firmware, but if you delete it, it turns out our startup scripts symlink it back to the wcnss firmware in /firmware/image. I managed to locate the current mako wcnss files, in the modem image and transferred them. The prima driver will not load with them either. It will only load with the default Relay firmware. I'm going to try a build with insecure riva off maybe.

**Comment by infernix** [comment]
I have backported prima 3.2.3.114 here https://github.com/TeamApexQ/android_kernel_samsung_apexq/tree/cm-10.1-prima-3.2.3.114 but it will not load due to an API mismatch.

The real problem however is that none of the other wcnss.\* firmware files work, not even the T699 JB stock firmware. This firmware determines what driver API level is supported, but it also is very much board specific it seems. I have tried new mako firmware, old mako firmware, oppo find 5 firmware, all to no avail with this driver.

What is _really_ strange is that the T699 JB stock firmware doesn't even load. And since it loads real early (pil loads it), it does not have anything to do with the prima_wlan driver.

**Comment by lbdroid** [comment]
This improvement has been incorporate into 3.4 builds.

**Comment by xboxfanj** [comment]
Use the drivers/staging/prima/FIRMWARE_BIN files in your device source as your WCNSS firmware. Those are the most up to date.  Maybe use this commit as well https://github.com/TeamPlaceholder/android_kernel_lge_gee/commit/fafd7ea4c8654f8a4a9c7b58a568dee1823634cf
