### ISSUE TITLE
Long-press and key-repeat glitch

### ISSUE THREAD

**Issue by infernix** [TeamApexQ/apexq#17]
Occasionally it seems that all keys (including home button) behave as if you are long pressing it, or that the key-repeat delay becomes incredibly short (few ms).

We need to figure out where the setting is for key repeat delay (/sys?) and see if it has changed when this happens.

**Comment by infernix** [comment]
https://github.com/CyanogenMod/android_device_samsung_msm8960-common/commit/a9f44cd5597da078d76f2eec5784717e7ad69e73 could  be the fix. All builds since march 8th should have it, e.g. it shouldn't reoccur with nightlies past march 8th.

**Comment by lbdroid** [comment]
Fixed with patch above.
