### ISSUE TITLE
Camera lib wrapper

### ISSUE THREAD

**Issue by infernix** [TeamApexQ/apexq#18]
A wrapper library around the camera blobs would be very helpful, we can then drop any changes in framework_base and it would give us more room to play with. It's being worked on.

**Comment by nardholio** [comment]
Still needed?

**Comment by infernix** [comment]
This is in progress. lbcoder is working on it.

**Comment by nardholio** [comment]
Need to re-write setup-makefiles.sh in d2-common to support this. lbcoder's pull request to TheMuppets contains the necessary changes, but these files are generated, not hand-made, and the setup scripts should reflect this in case the vendor scripts are ever re-generated.

**Comment by nardholio** [comment]
rear camera video is grey on cm-10.2 when you repeatedly switch from still to video (takes about 5 times). Does not crash though, you can switch back to still and it works.
Switching from video to still on the front camera generates a soft crash, ie it properly closes the HAL and you can re-enter the app.

**Comment by lbdroid** [comment]
Nard's glitch there is outside of the scope of camera wrapper. Wrapper is complete and upstreamed. https://github.com/CyanogenMod/android_device_samsung_apexqtmo/commit/9d6d4275b0766b1d621c6236f03d7321a8751bf5
