### ISSUE TITLE
Unable to charge phone issue

### ISSUE THREAD

**Issue by infernix** [TeamApexQ/apexq#19]
Some people report that sometimes the phone doesn't want to charge.

We're going to need some log data on this. Suggest to use catlog (play store) and start recording, then plug in, then save relevant log data and submit here.

**Comment by nardholio** [comment]
The problem has been narrowed chargers that identify as USB (vice AC) and don't send the magic start signal to the phone. Chargers made for Apple products seem to be the worst offenders. Shouldn't be too hard to track down the responsible code in the kernel and tell it to charge anyway, even if it doesn't get the magic signal.

**Comment by infernix** [comment]
Seems that with https://github.com/TeamApexQ/android_kernel_samsung_apexq/commit/8a3405ba9a072e09a66682c859751cba7aa59cda in place, I don't have a charger that fails to charge the phone, so I can't reproduce currently.

**Comment by infernix** [comment]
Appears to be fixed in https://github.com/TeamApexQ/android_kernel_samsung_apexq/commit/3c9b02002a184f604caab871db439306844e707b
