### ISSUE TITLE
Torch widget force-closes

### ISSUE THREAD

**Issue by aglasgall** [TeamApexQ/apexq#2]
When I add a torch widget to a homescreen and tap it to enable the torch, it immediately crashes. Inspection of logs indicates that it's trying to use the wrong LED device file.

**Comment by lbdroid** [comment]
Should be fixed by https://github.com/TeamApexQ/android_device_samsung_apexq-common/commit/049bb45cde11b681224d9147e035a883f56c7104

**Comment by aglasgall** [comment]
Confirmed fixed as of this evening, closing.
