### ISSUE TITLE
bluetooth stop and start with bluedroid

### ISSUE THREAD

**Issue by infernix** [TeamApexQ/apexq#22]
need to check whether if it really gets properly turned off in hardware, this seems to be going wrong and might explain the increased battery drain compared to older builds

**Comment by nardholio** [comment]
Should be fixed now.

**Comment by infernix** [comment]
Confirmed fixed with https://github.com/TeamApexQ/android_device_samsung_apexqtmo/commit/3e194ab370cc4523b5851f2a85ed24cfc35551aa
