### ISSUE TITLE
Icons cut off in notification pulldown.

### ISSUE THREAD

**Issue by wedge11383** [TeamApexQ/apexq#23]
When AM/PM style is enabled as normal in Settings/System/Statusbar, the quick settings panel icon will be cutoff at the edge of the screen if there is a four digit time or a month or day of the week that is too long is currently displayed.

If you set the quick settings panel to be enabled with a quick pulldown, the notification switch icon will display properly at the upper left of the screen but if you hit it to go back to notifications, it will be cutoff and when when you toggle back to quick settings, the notification screen icon is now cutoff.

![1 Normal](https://f.cloud.github.com/assets/3782113/321247/b8465b6e-99aa-11e2-910c-d78ef8394e9b.png)
![2 After toggle](https://f.cloud.github.com/assets/3782113/321248/b84a21ea-99aa-11e2-9a3e-6c35506691d3.png)
![3 Toggle back](https://f.cloud.github.com/assets/3782113/321249/b857dac4-99aa-11e2-950a-2cc5a699db39.png)

**Comment by infernix** [comment]
This does not _seem_ to be an apexq specific issue. If anyone could confirm this on another cm-10.1 device, that would be helpful. Leaving open for now.

**Comment by wedge11383** [comment]
Confirmed same behavior on my newly 10.1 updated G2.  This was an issue in CM 10 but was corrected on the G2.  I assumed whatever fix those developers applied could help here.  I didn't realize the issue had reappeared across all 10.1 builds.  I should have tested first.
