### ISSUE TITLE
Front camera switching modes causes crash

### ISSUE THREAD

**Issue by infernix** [TeamApexQ/apexq#25]
Switching back and forth between photo and camcorder mode on front camera  causes a crash.

**Comment by lbdroid** [comment]
This is a CM upstream problem. I set the nightly camera to use aosp for the time being, build 140 should not exhibit this problem.

**Comment by infernix** [comment]
We're back at CM camera as AOSP caused more severe issues than the crash on front cam.

**Comment by infernix** [comment]
This is fixed. Can open up new issue for camera wrapper lib.
