### ISSUE TITLE
Make 3.4 kernel work

### ISSUE THREAD

**Issue by infernix** [TeamApexQ/apexq#28]
More info on what works and doesnt work is here: https://github.com/TeamApexQ/apexq/wiki/Board-info

cm-10.1-infernix-3.4 branch is properly initializing audio but there is an IRQ issue that stops it from actually playing anything. interrupts for the audio card are stuck at 0.

**Comment by nardholio** [comment]
I just found some code I missed/ignored my first pass through, relating to clocks. I don't know if bad clocks could make the interrupts not work but we'll find out.

**Comment by shareefalis** [comment]
DOIT

**Comment by lbdroid** [comment]
This issue has been solved.
