### ISSUE TITLE
Mic levels too low

### ISSUE THREAD

**Issue by infernix** [TeamApexQ/apexq#29]
<dsrtrck> [03:28:39] it seems the mic on this phone is way too low. any ideas on how i can increase the volume in calls, etc.?
<dsrtrck> [03:32:01] i am using cm-10.1-20130511-NIGHTLY-apexqtmo.zip
<dsrtrck> [04:40:07] i installed Smart Voice Recorder and disabled the device's auto gain control (AGC) and set gain factor to 226.0x and the mic tests work great but only in that app.  i installed hd2 mic control but it says "Your device is missing /proc/mic_level which is required to adjust mic levels..."

I've actually noticed the same, might just have to increase some percentages or toggle some mic gain flags in snd_msm file.

**Comment by infernix** [comment]
https://github.com/TeamApexQ/android_device_samsung_apexqtmo/commit/9a555826f1c1bf309d4e822682bf6a7fa2292374 is avaiable in nightlies 137 and up.

Need to watch user response, but should be good now that it matches other android devices.

**Comment by icnocop** [comment]
Thank you.

The mic volume is better, but it still seems too low for me.  I'm wondering why it's at 77% instead of 100% like ADC3?

Thank you.

**Comment by infernix** [comment]
At 100% it will clip and it will sound like a blown out speaker.

I've matched it with the dB levels of an i9100. If you can, grab Noise Meter from the market and compare your levels to another android phone. There should be very litle difference in dB between them.

**Comment by icnocop** [comment]
![picture 4-001 5](https://f.cloud.github.com/assets/507649/505322/c9bed9f8-bd1c-11e2-95f6-abc9f256be52.jpg)

http://tinypic.com/r/ao9ugg/5

Left: CyanogenMod 7.2.0 on HTC Vision (G2) 29dB
Right: CyanogenMod 10.1-20130513-NIGHTLY-apexqtmo on Samsung Galaxy S Relay 4G 17 dB

**Comment by infernix** [comment]
can you post a logcat that starts right before Noise Meter is started, and ends when it has recorded a few secondsl

**Comment by icnocop** [comment]
http://pastebin.com/aCtgG41F

Thank you.

**Comment by icnocop** [comment]
I noticed that my baseband version is not T699UVBMC5; should it be?

Model number: SGH-T699
Android version: 4.2.2
Baseband version: T699UVMA2
Kernel version: 3.0.73-cyanogenmod-g15ac6d8 jenkins@ls #3 Tue May 14 00:04:11 UTC 2013
CPU: ARMv7 Processor rev 4 (v71)
Memory: 745 MB
CyanogenMod version: 10.1-20130513-NIGHTLY-apextmo
Build date: Mon May 13 00:03:22 UTC 2013
Build number: cm_apexqtmo-userdebug 4.2.2 JDQ39E eng..20130513.000252 test-keys

**Comment by infernix** [comment]
Baseband really shouldn't matter. And apparently board revision doesn't either. I need to think of more things to look at.

**Comment by lbdroid** [comment]
Since this change, I've had people say that the volume coming through is excessively loud.

**Comment by infernix** [comment]
Shouldn't be since https://github.com/TeamApexQ/android_device_samsung_apexqtmo/commit/d08fcedd3021b3d24895ed242bb100bca52cab5c

**Comment by icnocop** [comment]
Hi guys,

In my particular case, it was a hardware issue.

I sent my device to Samsung for diagnostics \ repair and they confirmed it was a hardware issue.

Problem found:
TX AUDIO - MIC

Solution:
REPLACED COMPONENT 

Thank you. :)
