### ISSUE TITLE
USB OTG does not work

### ISSUE THREAD

**Issue by infernix** [TeamApexQ/apexq#30]
<Bracco> [23:31:10] it doesnt work btw
<Bracco> [23:31:34] and causes something else to hang, making mhl non functional until power cycle

**Comment by nardholio** [comment]
Please test again with 3.4 kernel.

**Comment by lbdroid** [comment]
There was otg init problems up to build 207 nightly. Since https://github.com/TeamApexQ/android_kernel_samsung_apexq/commit/79433dc4bd4d78ce8f33c607d2b2ece83b891112 it _might_ be fixed. Please confirm.

**Comment by lbdroid** [comment]
Fixored with http://review.cyanogenmod.org/#/c/47895/
