### ISSUE TITLE
Add Timeout Options for Hardware Key Backlight

### ISSUE THREAD

**Issue by mchelen** [TeamApexQ/apexq#32]
Currently there are options to enable/disable the backlight for the hardware keyboard and menu keys  in Settings > Advanced > Sensors.

Please add timeout options for both backlight settings. For example 30 sec, 1 min, 5 min, or never.

This would allow users more adaptability, such as keeping the keyboard permanently backlit, while hiding the menu keys quickly.

Thank you

**Comment by lbdroid** [comment]
That sounds like an upstream (cyanogenmod) feature request, beyond the scope of our project here.

**Comment by nardholio** [comment]
Not going to happen. Deviceparts are going away in 10.2. Anything like light timeouts has to go upstream.
