### ISSUE TITLE
Google Music crashes

### ISSUE THREAD

**Issue by westonbelk** [TeamApexQ/apexq#34]
Google Music crashes whenever I attempt to open the My Music or Radio tabs of the application. This does not occur in stock or AOKP (which was based on an earlier build of CM).  I used alogcat from the Play Store and got this http://pastebin.com/73Uav9yj

I am using the latest nightly.

**Comment by lbdroid** [comment]
The log does not indicate anything such as a "crash". Looks perfectly normal. Please test again with nightly build 194 or newer with all of your applications updated from market.

**Comment by westonbelk** [comment]
Tested with nightly build 195, issue persists. I will be flashing nightlies every couple of days and will report if the issue gets fixed with one.

**Comment by nardholio** [comment]
I am unable to reproduce this issue although there are multiple reports from xda of it. Please test again on build 200 or later.

**Comment by westonbelk** [comment]
Issue has been resolved as of build 200 (July 2nd)

I don't know if this was due to the new build or the update to the app that Google pushed on July 1st.

Edit: Thank you nardholio
