### ISSUE TITLE
USB charging slow

### ISSUE THREAD

**Issue by nardholio** [TeamApexQ/apexq#39]
BQ24157 seems to be stuck in safety mode, which draws only 100 mA of power. This is most likely because bq24157_charger_function_conrol is not getting called.

**Comment by infernix** [comment]
Might or might not be related to OTG.

**Comment by lbdroid** [comment]
This was determined to be only a current REPORTING problem. Charging was, in fact, at 500 mA. The reporting bug has been corrected.
