### ISSUE TITLE
Software keyboard doesn't show up

### ISSUE THREAD

**Issue by aglasgall** [TeamApexQ/apexq#4]
When I tap a text field, neither the Android software keyboard nor any other input method pops up.

**Comment by kornyone** [comment]
This should be fixed with the commit https://github.com/TeamApexQ/android_device_samsung_apexq-common/commit/74a54c81f26c7f3942d822151e5ec551d295e7d8.  I believe there's a lingering issue with keyboard input not being accepted on the lock screen.

Please confirm.  Thanks!

**Comment by aglasgall** [comment]
Confirmed fixed as of this evening, closing.
