### ISSUE TITLE
Wifi and Bluetooth do not work at the same time

### ISSUE THREAD

**Issue by nardholio** [TeamApexQ/apexq#40]
I have no idea what is causing this, when a bluetooth socket is cycled, it seems to cut out Wifi. Pandora switching songs seems to be especially effective at causing this.

Have already tried different WCNSS firmwares and driver versions. Believe problem to be elsewhere (bluetooth or sound code)

Possible things to try
https://github.com/CyanogenMod/android_kernel_google_msm/commit/cdd2f80725609e70456f6868c695ca82dc9897b1

**Comment by nardholio** [comment]
We also might need this, not necessarily related to this bug https://github.com/CyanogenMod/android_external_bluetooth_bluedroid/commit/43e696894f7b64186cb987852ad26a0ae5fb2e03

**Comment by nardholio** [comment]
After extensively looking at code with lbcoder, we've determined that all the code necessary for BTC exists in bluedroid and in prima. What we do not currently know is whether the appropriate modules are receiving the signals they need to co-exist. It's going to take a heavy debugging build and some logs to figure out if the signals are being received. It is also unknown at this time where the signals come from. I did a test with a BTC server I found on caf and found that nothing we currently have connects to it.
https://www.codeaurora.org/cgit/quic/la/platform/vendor/qcom-opensource/bluetooth/log/

**Comment by nardholio** [comment]
On further inspection, we're not even building the btc client libbt-btc https://github.com/CyanogenMod/android_external_bluetooth_bluedroid/blob/cm-10.2/btc/Android.mk
Commit for btc server, if we require it
https://github.com/nardholio/android_packages_apps_Bluetooth/commit/76ded42fd3409b3806fbdc3eb21d49c5dcd6dbe6

**Comment by mdmallardi** [comment]
This has been fixed in our CyanogenMod 11 builds through the application of new Wifi blobs.
