### ISSUE TITLE
Import new code from gogh kernel

### ISSUE THREAD

**Issue by nardholio** [TeamApexQ/apexq#41]
SPH-L300 has an MG5 release which is newer than our MC5 kernel. There appear to be minor ApexQ-related improvements
board-8960-camera.c
taos.c
mxt224e.c
the entire camera tree
Also, the ApexQ defconfig has compaction off instead of on like we have now.

(Also noticed, stock config sets CONFIG_USB_EHCI_MSM_HSIC to on, which we are not currently doing)

**Comment by nardholio** [comment]
also changes to 0xfafa code

**Comment by zx2c4** [comment]
+1

**Comment by nardholio** [comment]
current code is working fine.
