### ISSUE TITLE
TWRP does not work correctly

### ISSUE THREAD

**Issue by infernix** [TeamApexQ/apexq#47]
Most likely because of wifimac.sh that is ran in recovery; if it doesn't run correctly, updating from 10.1 to 10.2 with TWRP results in non-working wifi.

Either fix TWRP for 10.2, or amend wifimac.sh so it works with TWRP.

**Comment by lbdroid** [comment]
twrp is not supported.

**Comment by nardholio** [comment]
How hard would it be to create a new TWRP build, infernix?

**Comment by ameer1234567890** [comment]
@infernix How can I modify wifimac.sh ? Where is it?

**Comment by nardholio** [comment]
The old TWRP is definitely not compatible at this point. Build a new one yourself if you want an updated version.
