### ISSUE TITLE
CM recovery does not mount external sdcard

### ISSUE THREAD

**Issue by infernix** [TeamApexQ/apexq#48]
Workaround:

adb shell 'mkdir /data/media/1; mount /dev/block/mmcblk1p1 /data/media/1'

But this should not be needed.

**Comment by lbdroid** [comment]
missing from fstab, and narf refuses to fix it on principle.

**Comment by nardholio** [comment]
it's inherited from d2-common, you'd think they'd fix it ;p

**Comment by nardholio** [comment]
then again I did write the 4.3 fstab...

**Comment by nardholio** [comment]
cm-10.2 vold has been extensively fixed and recovery fstab is no longer required
