### ISSUE TITLE
Device powers off without warning, takes repeated attempts to turn it back on

### ISSUE THREAD

**Issue by RenaeMacLeod** [TeamApexQ/apexq#50]
Previously it was thought to be an issue with my SD card but it is happening without any apps installed or SD/SIM inserted. Phone will simply turn off, usually at around 42/43 degrees celsius.

**Comment by RenaeMacLeod** [comment]
The issue seems to be related to WiFi and/or BlueTooth. Last night I reinstalled 'cm-10.2-20131009-NIGHTLY-apexqtmo.zip' and literally only set up WiFi, my Google account, and turned off automatic screen rotate. I then installed NBench and ran it fully twice. The phone was quite hot but I had no temp software installed. I would then be able to crash the phone within about 15 minutes after that by repeatedly toggling BlueTooth off then on (while WiFi was already on) and running NBench for about 30 seconds between each toggle. Every few toggles I would force sync the Google account. There was no SIM or SD installed and no BT devices were paired. Also, once the phone was hot it would not turn on. It would get about (guessing) 10 seconds into the CyanogenMod spinning boot screen and freeze. Then after about another 10 seconds the phone would vibrate and it would reboot again. I have seen a solid blue screen with no text about 4 times over the past 2 weeks while dealing with this issue.

Adam had said that ThermalD was crashing and it was related to the SD card. I tried replacing thermald.conf with thermald-8960.conf without any noticable change. I then decided to take the ThermalD files (bin & etc) from my stable 'cm-10.1-20130309-UNOFFICIAL-apexqtmo' build. It seems to be more stable but it's still having issues when booting up. Removing the SD card and turning off WiFi/BT seems to help significantly.

I really hope this is helpful. If there is anything else I can do I am willing to do it, time permitting.

**Comment by RenaeMacLeod** [comment]
I can confirm that it's definitely more stable. I'ver heard that ThermalD is being replaced entirely and I look forward to it. In the meantime I would like to request that ThermalD from a pre 3.4 kernel be put in the build, if it's possible.

**Comment by nardholio** [comment]
Fixed with new thermal daemon.
