### ISSUE TITLE
Torch high brightness won't turn on

### ISSUE THREAD

**Issue by kornyone** [TeamApexQ/apexq#8]
Now that torch is functional, high brightness won't turn on.  It simply does nothing. 

It is worth noting that the Relay 4g has a brighter output without high brightness than my HTC Doubleshot with two lights for flash.

**Comment by nardholio** [comment]
Intentionally disabled in torch settings, I think it's boolean.. 0 or 1. I don't think we have a high brightness mode

**Comment by kornyone** [comment]
Fair enough.  I simply caught this during my stress testing.  Not a big concern at all.

Like I stated, the light is brighter than any phone I compared it to.    In my opinion, it should be OK the way it is.

**Comment by nardholio** [comment]
I noticed there is a high torch setting using the camera interface, but not using /sys. I see in overlay settings torch does support using the camera interface, we could try swapping that to see what happens

**Comment by infernix** [comment]
Doesn't seem to be a need for high brightness.
