### ISSUE TITLE
Something funky with automatic brightness control

### ISSUE THREAD

**Issue by aglasgall** [TeamApexQ/apexq#9]
I'm still poking around the outlines of what's going on here, but I'm reasonably sure that automatic brightness control isn't actually adjusting to a wide enough range of levels of illumination.

**Comment by kornyone** [comment]
I was playing with overlays which define the auto brightness values (device/samsung/apexq-common/overlay/frameworks/base/core/res/res/values/config.xml).  I used some values from Doubleshot, and the behavior was different.  I also noticed Comanche has this set differently.  I believe those values are responsible for this, as for me, auto brightness does adjust values... but not the way I remember stock/CM9 doing so on the Relay.

**Comment by nardholio** [comment]
I think we can close this?

**Comment by kornyone** [comment]
I am with closing this.
